blank_issues_enabled: false
contact_links:
    - name: Have questions or need support?
      url: https://github.com/Qazalbash/jaxampler/discussions
      about: Please ask questions on the Discussions tab
